name: End-to-End Tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      should_skip:
        required: false
        type: string

jobs:
  test:
    name: Test
    if: inputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        db:
          - mssql
          - mysql
          - postgres
          - maria
          - postgres10
          # - sqlite3
        node-version:
          - '16'
    env:
      CACHED_IMAGE: ghcr.io/directus/directus-e2e-test-cache:${{ matrix.node-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start databases containers
        run: docker compose up -d --wait --quiet-pull

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Run tests
        run: npm run test:e2e
        env:
          TEST_DB: ${{ matrix.db }}

  result:
    name: Result
    if: inputs.should_skip != 'true' && always()
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Mark result as failed
        if: needs.test.result != 'success'
        run: exit 1
